### ISSUE TITLE
Error Snapping Navigation Bar On Android 7.1.2

### ISSUE THREAD

**Issue by Ali382829** [Ali382829/DEMO#7]
Images

![Screenshot_20241116_141255_Virtual Master](https://github.com/user-attachments/assets/b526e268-102a-4179-bff1-cd03271a06ed)

Error Snapping Navigation Bar On Android 7.1.2 Due To System UI Issues
You Cannot Snapping Navigation Bar

**Comment by Ali382829** [comment]
Don't System UI Issues Before Snapping Navigation Bar

**Comment by Ali382829** [comment]
Change DPI To Snap Navigation Bar

**Comment by Ali382829** [comment]
Yes

**Comment by Ali382829** [comment]
#10

**Comment by alihyder56629** [comment]
You Can Charge DPI Before Snapping Navigation Bar

**Comment by alihyder56629** [comment]
Navigation Bar Snap Bugs
